services:
  db:
    image: postgres:17.2-alpine3.21
    container_name: "mini-delivery-db"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mini-delivery
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

networks:
  mini-delivery:
    driver: bridge
